### ISSUE TITLE
[Facebook SDK] Use Facebook APP if installed

### ISSUE THREAD

**Issue by ogabrielides** [ogabrielides/GameOd#17]
**Problem description**

Branch **master**

A) In the home page when the user presses the Facebook button, it opens the safari.
Make it open Facebook APP if installed. Safari otherwise
https://github.com/ogabrielides/GameOd/blob/master/GameOd/ViewControllers/InitScreenViewController.m
![screenshot 2018-02-16 23 56 29](https://user-images.githubusercontent.com/234844/36332108-8884e5be-1379-11e8-8270-625cd426b586.png)

B) Same for Share Facebook on the end of a game:
https://github.com/ogabrielides/GameOd/blob/master/GameOd/ViewControllers/EndOfGameViewController.m
![screenshot 2018-02-16 23 56 17](https://user-images.githubusercontent.com/234844/36332104-81b6de04-1379-11e8-9093-fb9f92ccf10c.png)

I am not sure, but I think this worked before. Maybe with the latest Facebook APP it doesn't work anymore

**Comment by vijay444** [comment]
Done

**Comment by ogabrielides** [comment]
Fixed
