### ISSUE TITLE
UI Small Fix

### ISSUE THREAD

**Issue by ogabrielides** [ogabrielides/GameOd#18]
**Problem Description**

Branch **master**

In the Rules Page (https://github.com/ogabrielides/GameOd/blob/master/GameOd/ViewControllers/RulesScreenViewController.m) we need to add margin on the left and right borders.

![screenshot 2018-02-17 00 09 51](https://user-images.githubusercontent.com/234844/36332188-e2ac575c-1379-11e8-85e4-4db15c4464f5.png)

**Comment by vijay444** [comment]
Done

**Comment by ogabrielides** [comment]
Fixed
